function [fx, Fx] = coordinatedTurnMotion(x, T)
%COORDINATEDTURNMOTION calculates the predicted state using a coordinated
%turn motion model, and also calculated the motion model Jacobian
% Your code here
px = x(1); 
py = x(2); 
v = x(3); 
phi = x(4);  
omega = x(5); 

fx = [px+T*v*cos(phi); ...
    py+T*v*sin(phi);...
    v;...
    phi+T*omega;...
    omega];
Fx = [1,0,T*cos(phi),-T*v*sin(phi),0; ...
    0,1,T*sin(phi),T*v*cos(phi),0;...
    0,0,1,0,0;...
    0,0,0,1,T;...
    0,0,0,0,1];
end